name: Deploy to AWS S3

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clear GitHub Actions cache
      run: |
        sudo apt-get remove actions/cache -y
        sudo apt-get autoremove -y
        sudo rm -rf /usr/share/dotnet/sdk/NuGetFallbackFolder/*
        sudo rm -rf /usr/share/dotnet/sdk/5.0.1/NuGetFallbackFolder/*
        sudo rm -rf /usr/share/dotnet/sdk/6.0.1/NuGetFallbackFolder/*
      if: runner.os == 'Linux'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://your-bucket-name --acl public-read --follow-symlinks --delete
      env:
        AWS_REGION: us-east-2  # Replace with your AWS region
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
