name: Deploy to AWS S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2  # Replace with your AWS region
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./personal-website  # Replace with the correct relative directory containing package.json

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://ishmael-personal-website --acl public-read --follow-symlinks --delete
      working-directory: ./personal-website  # Replace with the correct relative directory containing package.json
