name: Deploy to AWS S3

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: ${{ env.ACTIONS_ALLOW_UNSECURE_COMMANDS }}

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET_URL: s3://http://ishmael-personal-website.s3-website.us-east-2.amazonaws.com/  # Replace with your S3 bucket URL
        AWS_REGION: us-east-2  # Replace with your AWS region
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
